{% set major_minor = "2.8" %}
{% set version = major_minor + ".0" %}

package:
  name: libsigcpp
  version: {{ version }}

source:
  fn: libsigc++-{{ version }}.tar.xz
  url: http://ftp.acc.umu.se/pub/GNOME/sources/libsigc++/{{ major_minor }}/libsigc++-{{ version }}.tar.xz
  sha256: 774980d027c52947cb9ee4fac6ffe2ca60cc2f753068a89dfd281c83dbff9651

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - gcc  # [linux]
    - autoconf
    - automake
    - m4

  run:
    - libgcc  # [linux]

test:
  commands:
    - test -f ${PREFIX}/lib/libsigc-2.0.so  # [linux]
    - test -f ${PREFIX}/lib/libsigc-2.0.dylib  # [osx]

about:
  home: http://libsigc.sourceforge.net/
  license: GNU Lesser General Public License v3
  summary: "libsigc++ implements a typesafe callback system for standard C++."

extra:
  recipe-maintainers:
    - scopatz
