{% set version = "2.10.3" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}
{% set abi_version = "2.0" %}

package:
  name: libsigcpp
  version: {{ version }}

source:
  fn: libsigc++-{{ version }}.tar.xz
  url: http://ftp.acc.umu.se/pub/GNOME/sources/libsigc++/{{ major_minor }}/libsigc++-{{ version }}.tar.xz
  sha256: 0b68dfc6313c6cc90ac989c6d722a1bf0585ad13846e79746aa87cb265904786

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - sigcpp-{{ abi_version }} >={{ version }}

outputs:
  - name: sigcpp-{{ abi_version }}
    script: build_libsigcpp.sh
    build:
      run_exports:
        - sigcpp-{{ abi_version }} >={{ version }}
    requirements:
      build:
        - autoconf
        - automake
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - m4
      run_constrained:
        - libsigcpp {{ version }}
    test:
      commands:
        - test -f ${PREFIX}/lib/libsigc-{{ abi_version }}${SHLIB_EXT}

  - name: libsigcpp
    requirements:
      run:
        - sigcpp-{{ abi_version }}  {{ version }}
    test:
      commands:
        - test -f ${PREFIX}/lib/pkg-config/sigc++-{{ abi_version }}.pc

about:
  home: http://libsigc.sourceforge.net/
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: "libsigc++ implements a typesafe callback system for standard C++."

extra:
  recipe-maintainers:
    - scopatz
    - isuruf
