travis:
  secure:
    BINSTAR_TOKEN: bXN/jCLuouQSXwTt7Xu2eyWOrsYGeL6AyUxmIP0UJwXF2bkZkwyqXVwEAtByi1q7UoTYjdf3fDJu080twrMK3wK1sJR4FvCvokEOOGk0Vd9URlqe/RSYpSWwJzUgpQyZJh55ajhSV/dFc5EdyJ6K7lEG3FeKl0h3PwG5vXzOEUZkYguCzGuzOTGgnuVHPgPo5PdrO3zA/omlI4o5jUQPTKzZB6Fojkhc7a/ka4+C06urwS8qjAnq8saAunCmujPDgi0/182lQfQ8BXrO67PrsHyHMW6PCq9+o9qEzXTtQTXMlN92PRBNIZmZ4j8o66VWDLlzmTdP7gHSH03YcBXQlJd9br+WSd22tBow1P53+yDYuFm6KAUSezgQwp3BUi7yTVVoxBVz6BVrI2vWToQwY+XW6dIEvGi9B71VSVtf1xqo2AjN6bdVtapaQ1ix7galJVESPLtXe4Bk8G5hXn8hQR587dQz7IIhJy6vc703cLz+3vhDysT+UwUKmUPdpN301KyNKro2VrI+X9pKPDbLx+CPAiagN+wUz1UrPDC426xZmjBRDA9v6GX5UMhBOv4urKExbWRrRpKMUlcD7ydQLG/xSzdBVu3ASiegpc9ympnXPxgProZuVVii9Iy9jAW7eGQcn243/6yOKu9mejm9MPDPFOSMGgEapNJiKO3BhUs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
