travis:
  secure:
    BINSTAR_TOKEN: CoqNGvqxSWzJt3xZ1U0ju9idjcOtXPUwr2REJDhPCj6rcTIVdkqgq1EAQyWxrOdihIcxNLIdaiqTtBMSM57Stf1bTlP2mPFzBTarw5Erm0d9plbawXONK1RpmbgywpVzBb0uwsBsOXJeOR8m8dZ6LUv221iL0QxnpYfj3L2HnlTxXYkiKvwUUKSsw93r5wCYVeQ0iGg+bFOLkxhv4sE3nKoyLegd9VQQD0d0ajqFrNp+t3yU6kt/hR8Iq6J23WFr3Q/j5gafe11TLtZspLbxF9ljYI6nzGAjjUvFBdeeyHTyYahNpF2SHAnwO8d5EClcgLrWws56PCuiXbILjjHSxFGpN2DIHciBef+JSpse8+jgC5pm7Fg+2KDKGRH94f2wpU3AYhN7FV7GfkRZMjVexNAOjMu5l02uTij0RkIOSo75mu9Hcg66SC72cNO6VoYfLbm5jEzRhIJpsVhC5bX5EzDjgFckVOnOVXQfJiiVVuLJ1PWEV0YTi08t2h2xLq3wlT3dIENp+DpeUuQ18c1C8F5oCPuFDOeTMy4nMrs41f3zxVvtdIaHbpQak95Ux5fgX3IGkSzdVCYh+HYN3b2Ij4K+JkSn1T9m+kW4P7XvkAJhEhXkOQDDt4MRBTTRkiScnutApOJlM7i60bndOyN+FhNcbGopegPYOs3Seuw8Ncs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
